version: '3.6'

services:
  postgres:
    image: postgres
    container_name: postgres-for-quarkus
    hostname: postgres
    privileged: true
    env_file: .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    restart: unless-stopped

  rest-db:
    container_name: quarkus-rest-db
    hostname: rest-db
    depends_on:
      - postgres
    tty: true
    privileged: true
    env_file: .env
    build:
      context: .devcontainer/docker
      dockerfile: dockerfile
      args:
        - QUARKUS_VERSION=${QUARKUS_VERSION}
        - WORK_DIR=${WORK_DIR}
    volumes:
      - .:/app:cached
    restart: "no"

  rest-git:
    container_name: quarkus-rest-git
    hostname: rest-git
    tty: true
    privileged: true
    env_file: .env
    build:
      context: .devcontainer/docker
      dockerfile: dockerfile
      args:
        - QUARKUS_VERSION=${QUARKUS_VERSION}
        - WORK_DIR=${WORK_DIR}
    volumes:
      - .:/app:cached
      - restgit_volume:/var/git
    restart: "no"

  rest-backend:
    container_name: quarkus-rest-backend
    hostname: rest-backend
    tty: true
    privileged: true
    env_file: .env
    build:
      context: .devcontainer/docker
      dockerfile: dockerfile
      args:
        - QUARKUS_VERSION=${QUARKUS_VERSION}
        - WORK_DIR=${WORK_DIR}
    volumes:
      - .:/app:cached
    restart: "no"

  ui-frontend:
    container_name: quarkus-ui-frontend
    hostname: ui-frontend
    tty: true
    privileged: true
    env_file: .env
    build:
      context: .devcontainer/docker
      dockerfile: dockerfile
      args:
        - QUARKUS_VERSION=${QUARKUS_VERSION}
        - WORK_DIR=${WORK_DIR}
    volumes:
      - .:/app:cached
    restart: "no"

volumes:
  restgit_volume:
    driver: local
  postgres_volume:
    driver: local
