FROM ghcr.io/graalvm/native-image:muslib-ol8-java17

ARG QUARKUS_VERSION
# dirs
ARG WORK_DIR

RUN set -xeu
RUN echo "root:password" | chpasswd

RUN microdnf install -y wget zip unzip vim git curl

# Quarkus CLI
RUN mkdir /opt/quarkus && \
    wget --no-check-certificate --no-cookies -O - "https://github.com/quarkusio/quarkus/releases/download/${QUARKUS_VERSION}.Final/quarkus-cli-${QUARKUS_VERSION}.Final.tar.gz" | \
    tar -zxC ${WORK_DIR} && \
    mv -fu ${WORK_DIR}/quarkus-cli-${QUARKUS_VERSION}.Final/* /opt/quarkus
ENV PATH $PATH:/opt/quarkus/bin

ENTRYPOINT ["/bin/sh"]
