global:
  scrape_interval: 10s
  external_labels:
    system: quarkus-sample

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: rest-db
    metrics_path: /q/metrics
    honor_labels: true
    static_configs:
      - targets: ['rest-db-jvm:8081']
        labels:
          app: rest-db
          application: db-service
          system: quarkus-sample

  - job_name: rest-backend
    metrics_path: /q/metrics
    honor_labels: true
    static_configs:
      - targets: ['rest-backend-jvm:8082']
        labels:
          app: rest-backend
          application: backend-service
          system: quarkus-sample
