version: '3.6'

services:
  db-local:
    image: postgres
    container_name: db-local-for-quarkus
    privileged: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports: 
      - 5432:5432
    volumes:
      - ../db_init/initialize-database.js:/docker-entrypoint-initdb.d/1-init-db.js
    restart: unless-stopped

  gitlab-local:
    image: gitlab/gitlab-ce:16.8.2-ce.0
    container_name: gitlab-local-for-quarkus
    privileged: true
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8000'
        registry_external_url 'http://localhost:5050'
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['time_zone'] = "Asia/Tokyo"
        gitlab_rails['initial_root_password'] = "P@ssw0rd"
        nginx['listen_port'] = 8000
        puma['worker_processes'] = 1
        postgresql['shared_buffers'] = "1024MB"
        mattermost['enable'] = false
        prometheus['enable'] = false
        alertmanager['enable'] = false
        node_exporter['enable'] = false
        redis_exporter['enable'] = false
        postgres_exporter['enable'] = false
        gitlab_exporter['enable'] = false
        grafana['enable'] = false
    volumes:
      - gitlab-local_config:/etc/gitlab
      - gitlab-local_logs:/var/log/gitlab
      - gitlab-local_data:/var/opt/gitlab
    logging:
      options:
        max-size: "4M"
        max-file: "14"
    ports:
      - 8000:8000
      - 5050:5050
    restart: unless-stopped

  rest-db-jvm:
    image: docker.io/quarkus/rest-db-jvm:latest
    container_name: quarkus-rest-db-jvm
    depends_on:
      - db-local
    ports:
      - 8081:8081
    environment:
      QUARKUS_LOG_HANDLER_GELF_HOST: graylog
      QUARKUS_LOG_HANDLER_GELF_PORT: 12201
      QUARKUS_DATASOURCE_REACTIVE_URL: vertx-reactive:postgresql://db-local:5432/postgres
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4317
    restart: "no"
    networks:
      default:
        aliases:
          - rest-db-jvm

  rest-git-jvm:
    image: docker.io/quarkus/rest-git-jvm:latest
    container_name: quarkus-rest-git-jvm
    ports:
      - 8082:8082
    environment:
      QUARKUS_LOG_HANDLER_GELF_HOST: graylog
      QUARKUS_LOG_HANDLER_GELF_PORT: 12201
      QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4317
      GIT_REPOSITORY_REMORE_URL: http://gitlab-local:8000/root/myrepo.git
      GIT_REPOSITORY_LOCAL_PATH: /var/git/myrepo/
    restart: "no"
    volumes:
      - rest_git_volume:/var/git
    networks:
      default:
        aliases:
          - rest-git-jvm

  rest-backend-jvm:
    image: docker.io/quarkus/rest-backend-jvm:latest
    container_name: quarkus-rest-backend-jvm
    ports:
      - 8083:8083
    environment:
      QUARKUS_LOG_HANDLER_GELF_HOST: graylog
      QUARKUS_LOG_HANDLER_GELF_PORT: 12201
      QUARKUS_REST-CLIENT_RESTDB-API_URL: http://rest-db-jvm:8081
      QUARKUS_REST-CLIENT_RESTGIT-API_URL: http://rest-git-jvm:8082
      QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4317
    restart: "no"
    networks:
      default:
        aliases:
          - rest-backend-jvm

  ui-frontend-jvm:
    image: docker.io/quarkus/ui-frontend-jvm:latest
    container_name: quarkus-ui-frontend-jvm
    depends_on:
      - rest-backend-jvm
    ports:
      - 8080:8080
    restart: "no"
    environment:
      API_BASE_URL: http://localhost:8083
      QUARKUS_QUINOA_INDEX_PAGE: quinoa.html
      QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4317

volumes:
  gitlab-local_config:
    driver: local
  gitlab-local_logs:
    driver: local
  gitlab-local_data:
    driver: local
  rest_git_volume:
    driver: local